import type { VibeScene } from "./scene-schema.ts";

const now = "2026-01-01T00:00:00.000Z";

export function createStarterScene(): VibeScene {
  return {
    format: "vibe-3d/1",
    version: 1,
    id: "scene-product-study",
    name: "Product form study",
    unit: "m",
    background: "#111014",
    environment: "studio",
    quality: {
      target: "balanced",
      notes: ["清晰的主轮廓", "可拆分的功能部件", "适合实时浏览器预览"],
    },
    createdAt: now,
    updatedAt: now,
    nodes: [
      {
        id: "body",
        name: "Body shell",
        type: "mesh",
        parentId: null,
        visible: true,
        locked: false,
        fidelity: "macro",
        transform: { position: [0, 0.12, 0], rotation: [0, 0, 0], scale: [1, 1, 1] },
        geometry: { kind: "box", width: 2.35, height: 1.36, depth: 0.74, bevel: 0.22 },
        material: {
          color: "#d8d4e5", metalness: 0.22, roughness: 0.28, opacity: 1, transparent: false,
          wireframe: false, emissive: "#000000", emissiveIntensity: 0, clearcoat: 0.62, clearcoatRoughness: 0.18,
        },
        castShadow: true,
        receiveShadow: true,
      },
      {
        id: "lens-ring",
        name: "Control ring",
        type: "mesh",
        parentId: null,
        visible: true,
        locked: false,
        fidelity: "meso",
        transform: { position: [0, 0.15, 0.49], rotation: [0, 0, 0], scale: [1, 1, 1] },
        geometry: { kind: "torus", radius: 0.46, tube: 0.12, radialSegments: 24, tubularSegments: 72 },
        material: {
          color: "#6650a4", metalness: 0.84, roughness: 0.24, opacity: 1, transparent: false,
          wireframe: false, emissive: "#000000", emissiveIntensity: 0, clearcoat: 0.25, clearcoatRoughness: 0.2,
        },
        castShadow: true,
        receiveShadow: true,
      },
      {
        id: "lens",
        name: "Lens glass",
        type: "mesh",
        parentId: null,
        visible: true,
        locked: false,
        fidelity: "meso",
        transform: { position: [0, 0.15, 0.5], rotation: [90, 0, 0], scale: [1, 1, 1] },
        geometry: { kind: "cylinder", radiusTop: 0.39, radiusBottom: 0.39, height: 0.22, radialSegments: 64, openEnded: false },
        material: {
          color: "#29223b", metalness: 0.34, roughness: 0.08, opacity: 0.88, transparent: true,
          wireframe: false, emissive: "#171125", emissiveIntensity: 0.2, clearcoat: 1, clearcoatRoughness: 0.05,
        },
        castShadow: true,
        receiveShadow: true,
      },
      {
        id: "shutter",
        name: "Shutter",
        type: "mesh",
        parentId: null,
        visible: true,
        locked: false,
        fidelity: "micro",
        transform: { position: [0, 0.84, 0.08], rotation: [0, 0, 0], scale: [1, 1, 1] },
        geometry: { kind: "cylinder", radiusTop: 0.15, radiusBottom: 0.17, height: 0.12, radialSegments: 32, openEnded: false },
        material: {
          color: "#6650a4", metalness: 0.74, roughness: 0.3, opacity: 1, transparent: false,
          wireframe: false, emissive: "#000000", emissiveIntensity: 0, clearcoat: 0.22, clearcoatRoughness: 0.3,
        },
        castShadow: true,
        receiveShadow: true,
      },
      {
        id: "key-light",
        name: "Key light",
        type: "light",
        lightKind: "directional",
        parentId: null,
        visible: true,
        locked: false,
        fidelity: "macro",
        transform: { position: [4, 6, 5], rotation: [0, 0, 0], scale: [1, 1, 1] },
        color: "#fff8ef",
        intensity: 3.2,
        distance: 0,
        angle: 0.5,
        penumbra: 0.2,
        castShadow: true,
      },
      {
        id: "fill-light",
        name: "Fill light",
        type: "light",
        lightKind: "point",
        parentId: null,
        visible: true,
        locked: false,
        fidelity: "macro",
        transform: { position: [-4, 2, 2], rotation: [0, 0, 0], scale: [1, 1, 1] },
        color: "#bcaef4",
        intensity: 5,
        distance: 12,
        angle: 0.5,
        penumbra: 0.2,
        castShadow: false,
      },
    ],
  };
}
